#encoding: utf-8
##################################################
# file: DocumentationService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      wsdl2py --complexType ../../openorange/routines/DocumentationWebServices.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from DocumentationService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
AppendDocumentationSoapIn = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "AppendDocumentationRequestObject").pyclass

AppendDocumentationSoapOut = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "AppendDocumentationResponseObject").pyclass

GetDocumentationSoapIn = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "GetDocumentationRequestObject").pyclass

GetDocumentationSoapOut = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "GetDocumentationResponseObject").pyclass

GetIndexSoapIn = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "GetIndexRequestObject").pyclass

GetIndexSoapOut = GED("http://www.openorange.com.ar/WSSpecification/DocumentationServices", "GetIndexResponseObject").pyclass


# Service Skeletons
class DocumentationService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/WSActions/DocumentationServices.py', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_AppendDocumentation(self, ps, **kw):
        request = ps.Parse(AppendDocumentationSoapIn.typecode)
        return request,AppendDocumentationSoapOut()

    soapAction['http://www.openorange.com.ar/AppendDocumentation'] = 'soap_AppendDocumentation'
    root[(AppendDocumentationSoapIn.typecode.nspname,AppendDocumentationSoapIn.typecode.pname)] = 'soap_AppendDocumentation'

    def soap_GetDocumentation(self, ps, **kw):
        request = ps.Parse(GetDocumentationSoapIn.typecode)
        return request,GetDocumentationSoapOut()

    soapAction['http://www.openorange.com.ar/GetDocumentation'] = 'soap_GetDocumentation'
    root[(GetDocumentationSoapIn.typecode.nspname,GetDocumentationSoapIn.typecode.pname)] = 'soap_GetDocumentation'

    def soap_GetIndex(self, ps, **kw):
        request = ps.Parse(GetIndexSoapIn.typecode)
        return request,GetIndexSoapOut()

    soapAction['http://www.openorange.com.ar/GetIndex'] = 'soap_GetIndex'
    root[(GetIndexSoapIn.typecode.nspname,GetIndexSoapIn.typecode.pname)] = 'soap_GetIndex'

